/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hafidz Lazuardi
 */
public class Hal_Tentor extends javax.swing.JFrame {

    /**
     * Creates new form Hal_Tentor
     */
    public Hal_Tentor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTentorid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTentorName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTentorumur = new javax.swing.JTextField();
        btnPeriksa = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        editTentorTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableKT = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        PanelBuatMateri = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        judulMateriTxt = new javax.swing.JTextField();
        btnCreateMateri = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        kodeMateriTxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TableMateri = new javax.swing.JTable();
        PanelHapusMateri = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        HapusMateriTxt = new javax.swing.JTextField();
        BtnHapusMateri = new javax.swing.JButton();
        PanelUpdateMateri = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        KodeMateriEditTxt = new javax.swing.JTextField();
        BtnCariMateri = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        GantiNamaMateriTxt = new javax.swing.JTextField();
        BtnGantiMateri = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        GantiKodeMateriTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        nameEditTxt = new javax.swing.JTextField();
        umurEditTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnEditTentor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Halaman Tentor");

        jLabel2.setText("ID");

        tfTentorid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTentoridActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        tfTentorName.setEditable(false);

        jLabel4.setText("Umur");

        tfTentorumur.setEditable(false);
        tfTentorumur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTentorumurActionPerformed(evt);
            }
        });

        btnPeriksa.setText("Periksa");

        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        editTentorTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editTentorTabMousePressed(evt);
            }
        });

        TableKT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama Student", "Nama Kelas"
            }
        ));
        jScrollPane4.setViewportView(TableKT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editTentorTab.addTab("Kelas yang Ditugaskan", jPanel1);

        jLabel5.setText("Judul Materi");

        btnCreateMateri.setText("Create");

        jLabel9.setText("Kode Materi");

        javax.swing.GroupLayout PanelBuatMateriLayout = new javax.swing.GroupLayout(PanelBuatMateri);
        PanelBuatMateri.setLayout(PanelBuatMateriLayout);
        PanelBuatMateriLayout.setHorizontalGroup(
            PanelBuatMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuatMateriLayout.createSequentialGroup()
                .addGroup(PanelBuatMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuatMateriLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCreateMateri))
                    .addGroup(PanelBuatMateriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelBuatMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuatMateriLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(judulMateriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelBuatMateriLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kodeMateriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        PanelBuatMateriLayout.setVerticalGroup(
            PanelBuatMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuatMateriLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelBuatMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(kodeMateriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelBuatMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judulMateriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnCreateMateri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Create", PanelBuatMateri);

        TableMateri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama Materi", "Kode Materi"
            }
        ));
        jScrollPane6.setViewportView(TableMateri);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("View", jPanel6);

        jLabel15.setText("Kode Materi");

        BtnHapusMateri.setText("Hapus");

        javax.swing.GroupLayout PanelHapusMateriLayout = new javax.swing.GroupLayout(PanelHapusMateri);
        PanelHapusMateri.setLayout(PanelHapusMateriLayout);
        PanelHapusMateriLayout.setHorizontalGroup(
            PanelHapusMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHapusMateriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(26, 26, 26)
                .addComponent(HapusMateriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHapusMateri, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelHapusMateriLayout.setVerticalGroup(
            PanelHapusMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHapusMateriLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelHapusMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(HapusMateriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapusMateri))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Delete", PanelHapusMateri);

        jLabel13.setText("Cari Kode Materi");

        BtnCariMateri.setText("Cari");

        jLabel14.setText(" Ganti Nama Materi");

        GantiNamaMateriTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GantiNamaMateriTxtActionPerformed(evt);
            }
        });

        BtnGantiMateri.setText("Ganti");

        jLabel16.setText("Ganti Kode Materi");

        GantiKodeMateriTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GantiKodeMateriTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelUpdateMateriLayout = new javax.swing.GroupLayout(PanelUpdateMateri);
        PanelUpdateMateri.setLayout(PanelUpdateMateriLayout);
        PanelUpdateMateriLayout.setHorizontalGroup(
            PanelUpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUpdateMateriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelUpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14))
                .addGap(49, 49, 49)
                .addGroup(PanelUpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GantiKodeMateriTxt)
                    .addComponent(KodeMateriEditTxt)
                    .addComponent(GantiNamaMateriTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelUpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnGantiMateri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCariMateri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelUpdateMateriLayout.setVerticalGroup(
            PanelUpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUpdateMateriLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelUpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(KodeMateriEditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCariMateri))
                .addGap(4, 4, 4)
                .addGroup(PanelUpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GantiKodeMateriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(8, 8, 8)
                .addGroup(PanelUpdateMateriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GantiNamaMateriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnGantiMateri)
                    .addComponent(jLabel14))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Update", PanelUpdateMateri);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        editTentorTab.addTab("CRUD Materi", jPanel3);

        jLabel10.setText("Name");

        jLabel11.setText("Umur");

        btnEditTentor.setText("Ubah");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameEditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(umurEditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEditTentor)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(nameEditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(umurEditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(btnEditTentor)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        editTentorTab.addTab("Edit Akun", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LogoutBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(204, 204, 204))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(editTentorTab))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTentorumur, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTentorid, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(tfTentorName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPeriksa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfTentorid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTentorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(btnPeriksa, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfTentorumur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(editTentorTab, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(LogoutBtn)
                .addContainerGap())
        );

        setBounds(700, 230, 540, 567);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void tfTentoridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTentoridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTentoridActionPerformed

    private void tfTentorumurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTentorumurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTentorumurActionPerformed

    private void editTentorTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editTentorTabMousePressed

    }//GEN-LAST:event_editTentorTabMousePressed

    private void GantiKodeMateriTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GantiKodeMateriTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GantiKodeMateriTxtActionPerformed

    private void GantiNamaMateriTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GantiNamaMateriTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GantiNamaMateriTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //Panel Tentor
    
        
    public String getSelectedTentorId(){
        return tfTentorid.getText();
    }
    
    public void setTentorName(String name){
        tfTentorName.setText(name);
    }
    
    public void setTentorNameEdit(String name){
        nameEditTxt.setText(name);
    }
    
    public void setTentorAge(int age){
        tfTentorumur.setText(String.valueOf(age));
    }
    
    public void setTentorAgeEdit(int age){
        umurEditTxt.setText(String.valueOf(age));
    }
    
    public String getid(){
        return tfTentorid.getText();
    }
    
    public String getNama(){
        return tfTentorName.getText();
    }
    
    public int getUmur(){
        int age = Integer.parseInt(tfTentorumur.getText());
        return age;
    }
    
    public String getNamaEdit(){
        return nameEditTxt.getText();
    }
    
    public int getUmurEdit(){
        int age = Integer.parseInt(umurEditTxt.getText());
        return age;
    }
    //end of Panel Tentor
    
    //Panel Materi

    public void setGantiKodeMateriTxt(String kode) {
        this.GantiKodeMateriTxt.setText(kode);
    }

    public void setGantiNamaMateriTxt(String nama) {
        this.GantiNamaMateriTxt.setText(nama);
    }
    
    public String getSelectedKodemat(){
        return KodeMateriEditTxt.getText();
    }

    public String getSelectedKodematHapus(){
        return HapusMateriTxt.getText();
    }
    
    public String getGantiKodeMateriTxt() {
        return GantiKodeMateriTxt.getText();
    }

    public String getGantiNamaMateriTxt() {
        return GantiNamaMateriTxt.getText();
    }

    public String getHapusMateriTxt() {
        return HapusMateriTxt.getText();
    }

    public String getJudulMateriTxt() {
        return judulMateriTxt.getText();
    }

    public String getKodeMateriTxt() {
        return kodeMateriTxt.getText();
    }
    
    public void addActionListener(ActionListener al){
        btnPeriksa.addActionListener(al);
        btnEditTentor.addActionListener(al);
        btnCreateMateri.addActionListener(al);
        BtnHapusMateri.addActionListener(al);
        BtnCariMateri.addActionListener(al);
        BtnGantiMateri.addActionListener(al);
        LogoutBtn.addActionListener(al);
    }
    
    public JButton getBtnPeriksa(){
        return btnPeriksa;
    }
    
    public JButton getBtnEdit(){
        return btnEditTentor;
    }
    
    public JButton getBtnPeriksaMateri(){
        return BtnCariMateri;
    }
    
    public JButton getBtnHapusMateri(){
        return BtnHapusMateri;
    }
    
    public JButton getBtnGantiMateri(){
        return BtnGantiMateri;
    }
    
    public JButton getBtnCreateMateri(){
        return btnCreateMateri;
    }
    
    public JTable getTblStu() {
        return TableMateri;
    }
    
    public JTable getTblKT(){
        return TableKT;
    }

    public JButton getLogoutBtn() {
        return LogoutBtn;
    }
    
    public void setTableKT(String[][] ar2) {
//        for(int ss = 0; ss < ar2.length; ss++) {
//            System.out.println(ar2[ss][0]);
//            System.out.println(ar2[ss][1]);
//        }
        DefaultTableModel mdlTableKT = (DefaultTableModel) getTblKT().getModel();
        mdlTableKT.setRowCount(0);
        if (ar2 != null) {
            for (int i = 0; i < ar2.length; i++) {
                mdlTableKT.addRow(new Object[]{});
                TableKT.setValueAt(ar2[i][0], i, 0);
                TableKT.setValueAt(ar2[i][1], i, 1);
            }
        }
    }
    
//    public void setListTentorId(String[] listId){
//        ListTentor.setListData(listId);
//    }
//    
//    public String getSelectedTentorId(){
//        return ListTentor.getSelectedValue();
//    }
//    
//    public void setTentorString(String s){
//        taTentor.setText(s);
//    }
//    
//    public JList getListTentorId(){
//        return ListTentor;
//    }
//    
//    
//    public void addMouseAdapter(MouseAdapter ma){
//        ListTentor.addMouseListener(ma);
//    }
    
    public void resetView(){
        tfTentorName.setText(" ");
        tfTentorumur.setText(" ");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCariMateri;
    private javax.swing.JButton BtnGantiMateri;
    private javax.swing.JButton BtnHapusMateri;
    private javax.swing.JTextField GantiKodeMateriTxt;
    private javax.swing.JTextField GantiNamaMateriTxt;
    private javax.swing.JTextField HapusMateriTxt;
    private javax.swing.JTextField KodeMateriEditTxt;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JPanel PanelBuatMateri;
    private javax.swing.JPanel PanelHapusMateri;
    private javax.swing.JPanel PanelUpdateMateri;
    private javax.swing.JTable TableKT;
    private javax.swing.JTable TableMateri;
    private javax.swing.JButton btnCreateMateri;
    private javax.swing.JButton btnEditTentor;
    private javax.swing.JButton btnPeriksa;
    private javax.swing.JTabbedPane editTentorTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField judulMateriTxt;
    private javax.swing.JTextField kodeMateriTxt;
    private javax.swing.JTextField nameEditTxt;
    private javax.swing.JTextField tfTentorName;
    private javax.swing.JTextField tfTentorid;
    private javax.swing.JTextField tfTentorumur;
    private javax.swing.JTextField umurEditTxt;
    // End of variables declaration//GEN-END:variables
}
